version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_ibovespa
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ibovespa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: app_ibovespa
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ibovespa
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - .:/app
    command: python main.py

volumes:
  postgres_data:
